### ISSUE TITLE
Documentation or/and minimal working example?

### ISSUE THREAD

**Issue by JokerQyou** [phfaist/updater4pyi#3]
The documentation does not draw a clear workflow on how an application update procedure could be achieved, it only gives a list of available APIs. I have to say its effect is very limited. 
I think we need more detailed documentation, which should contain at least a workflow graph on how the update procedure should be done, or give a minimal example (whether a console app or a GUI app) which could work properly.

Right now I have an `upd_source.BinReleaseInfo` object and am trying to work with a `PyQt4` interface, but I could not get it to work, because I have no idea how all this is going.

**Comment by phfaist** [comment]
My time is currently very limited and I can't make big changes at the moment, although my long-term plan would be to improve the documentation. For a minimal working example, see http://updater4pyi.readthedocs.org/en/latest/quickstart/, which is meant to work with github releases.

Usually you don't have to deal with `BinReleaseInfo` objects directly. You should instantiate a _source_ appropriately (e.g. `upd_source.UpdateGithubReleasesSource`) to find new releases. Then instantiate a _core updater_ (`upd_core.Updater`) which takes care of downloading and installing updates with the source you provide it. Finally, instantiate an _interface_ (e.g. `upd_iface_pyqt4.UpdatePyQt4Interface`) which takes care of automatically scheduling the checks for the updater and showing dialogs to the user.

**Comment by JokerQyou** [comment]
Thanks for your reply! 

I've implemented an update schedule for my app already, the only thing I need now is to download an archive file and extract its content to properly overwrite current files inside the installation directory. But from my point of view, it's much too complicated if I'm really going to use this module. 
I think I'd better implement these functionalities my own way.

Thanks anyway.

**Comment by phfaist** [comment]
I must say I don't understand what you're trying to achieve. The process you're describing is taken care of already automatically by the `upd_core.Updater` object. Anyway, it's up to you.
